// Patients
export const CREATE_PATIENT_INDEXES_REQUEST = 'patients/CREATE_PATIENT_INDEXES_REQUEST';
export const CREATE_PATIENT_INDEXES_SUCCESS = 'patients/CREATE_PATIENT_INDEXES_SUCCESS';
export const CREATE_PATIENT_INDEXES_FAILED = 'patients/CREATE_PATIENT_INDEXES_FAILED';

export const CREATE_PATIENT_REQUEST = 'patients/CREATE_PATIENT_REQUEST';
export const CREATE_PATIENT_SUCCESS = 'patients/CREATE_PATIENT_SUCCESS';
export const CREATE_PATIENT_FAILED = 'patients/CREATE_PATIENT_FAILED';

export const FETCH_PATIENTS_REQUEST = 'patients/FETCH_PATIENTS_REQUEST';
export const FETCH_PATIENTS_SUCCESS = 'patients/FETCH_PATIENTS_SUCCESS';
export const FETCH_PATIENTS_FAILED = 'patients/FETCH_PATIENTS_FAILED';

export const FETCH_ADMITTED_PATIENTS_REQUEST = 'patients/FETCH_ADMITTED_PATIENTS_REQUEST';
export const FETCH_ADMITTED_PATIENTS_SUCCESS = 'patients/FETCH_ADMITTED_PATIENTS_SUCCESS';
export const FETCH_ADMITTED_PATIENTS_FAILED = 'patients/FETCH_ADMITTED_PATIENTS_FAILED';

export const FETCH_ONE_PATIENT_REQUEST = 'patients/FETCH_ONE_PATIENT_REQUEST';
export const FETCH_ONE_PATIENT_SUCCESS = 'patients/FETCH_ONE_PATIENT_SUCCESS';
export const FETCH_ONE_PATIENT_FAILED = 'patients/FETCH_ONE_PATIENT_FAILED';

export const DELETE_PATIENT_REQUEST = 'patients/DELETE_PATIENT_REQUEST';
export const DELETE_PATIENT_SUCCESS = 'patients/DELETE_PATIENT_SUCCESS';
export const DELETE_PATIENT_FAILED = 'patients/DELETE_PATIENT_FAILED';

export const CHECKIN_PATIENT_REQUEST = 'patients/CHECKIN_PATIENT_REQUEST';
export const CHECKIN_PATIENT_SUCCESS = 'patients/CHECKIN_PATIENT_SUCCESS';
export const CHECKIN_PATIENT_FAILED = 'patients/CHECKIN_PATIENT_FAILED';

export const GET_UPDATED_BIRTHDAY_REQUEST = 'patients/GET_UPDATED_BIRTHDAY_REQUEST';
export const GET_UPDATED_BIRTHDAY_SUCCESS = 'patients/GET_UPDATED_BIRTHDAY_SUCCESS';
export const GET_UPDATED_BIRTHDAY_FAILED = 'patients/GET_UPDATED_BIRTHDAY_FAILED';

export const GET_UPDATED_REFERDATE_REQUEST = 'patients/GET_UPDATED_REFERDATE_REQUEST';
export const GET_UPDATED_REFERDATE_SUCCESS = 'patients/GET_UPDATED_REFERDATE_SUCCESS';
export const GET_UPDATED_REFERDATE_FAILED = 'patients/GET_UPDATED_REFERDATE_FAILED';

// Medications
export const CREATE_MEDICATION_REQUEST = 'medications/CREATE_PATIENT_REQUEST';
export const CREATE_MEDICATION_SUCCESS = 'medications/CREATE_PATIENT_SUCCESS';
export const CREATE_MEDICATION_FAILED = 'medications/CREATE_PATIENT_FAILED';

export const FETCH_MEDICATIONS_REQUEST = 'medications/FETCH_MEDICATIONS_REQUEST';
export const FETCH_MEDICATIONS_SUCCESS = 'medications/FETCH_MEDICATIONS_SUCCESS';
export const FETCH_MEDICATIONS_FAILED = 'medications/FETCH_MEDICATIONS_FAILED';

export const CREATE_DISPENSE_REQUEST = 'medications/CREATE_DISPENSE_REQUEST';
export const CREATE_DISPENSE_SUCCESS = 'medications/CREATE_DISPENSE_SUCCESS';
export const CREATE_DISPENSE_FAILED = 'medications/CREATE_DISPENSE_FAILED';

// Invoices
export const CREATE_INVOICE_REQUEST = 'invoices/CREATE_INVOICE_REQUEST';
export const CREATE_INVOICE_SUCCESS = 'invoices/CREATE_INVOICE_SUCCESS';
export const CREATE_INVOICE_FAILED = 'invoices/CREATE_INVOICE_FAILED';

export const FETCH_INVOICES_REQUEST = 'invoices/FETCH_INVOICES_REQUEST';
export const FETCH_INVOICES_SUCCESS = 'invoices/FETCH_INVOICES_SUCCESS';
export const FETCH_INVOICES_FAILED = 'invoices/FETCH_INVOICES_FAILED';

// Labs
export const CREATE_LAB_REQUEST = 'labs/CREATE_LAB_REQUEST';
export const CREATE_LAB_SUCCESS = 'labs/CREATE_LAB_SUCCESS';
export const CREATE_LAB_FAILED = 'labs/CREATE_LAB_FAILED';

export const FETCH_LABS_REQUEST = 'labs/FETCH_LABS_REQUEST';
export const FETCH_LABS_SUCCESS = 'labs/FETCH_LABS_SUCCESS';
export const FETCH_LABS_FAILED = 'labs/FETCH_LABS_FAILED';

export const CREATE_APPOINTMENT_REQUEST = 'appointments/CREATE_APPOINTMENT_REQUEST';
export const CREATE_APPOINTMENT_SUCCESS = 'appointments/CREATE_APPOINTMENT_SUCCESS';
export const CREATE_APPOINTMENT_FAILED = 'appointments/CREATE_APPOINTMENT_FAILED';
